language: node_js
sudo: false
node_js:
- '0.10'
script:
- npm test
deploy:
  api_key:
    secure: 6HMoEzJoQeqcDYIbfQcKCfvq1cZRShQQXtReobwQ7oej/JkTMyokmfXuGZqHri/mgbPSQy/vhE8W/3TRJgnFY9MP1KcoBDwo8hkFSQ7JuldVC1T8RGXmdWfayLg6l4QDWSwl1VOGJ3LmnGorilmFC7s/8zKF7ThMV5o0wKDSblmma3JEiS4Zh0wPSf3lF1sbAyovohsFS0jaMf0GpBWn8hdoEVlrB7tGGTizrOvyeCxFJWaI9FKzgf2gtuFh0r/VehWfv7C/QFWi8OSLenyAkRsuqPcs9pi6Svc60y01SIeXLk7QXDRs31tgYj3k/nHbTcDjt6ygHyS2P7fV+X2jA62KL6LAmWBy93VOKDNEOHTs7FXy5ZuBppmR3CpckZYRA+kJWpk1Ga2YQhNHkifcuDEaa7+mSHro69Dk24PVXjzNooBy2TPvTntR8D6KcQ1u7+AITs/KJEwkNPGISS5awyP6UF9ae12MQdjzaVo2Snr5KJAoauqiB2pewPG+I1r455ZLRffrr+CmC+z1vWOnVgWIoxi6YQkwyoM4Uvayw9cwcGCXKzCg6fhx+fVBQMHnko6tSl1wxVNp6P+REAIJ1tNUkrggKKykQ1MuLwHcYKnt53dI6gdIxheH660MWMcyviwEk9B7viYVY11uzEQQcmp6y9PkA7YZ3QMtsXioTKE=
