language: node_js
sudo: false
node_js:
- '0.10'
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Py2zNWcm1Z1lsobU/1hzRJ8D+r6+jRo6zI3zHeM9ZWjmd9f1qJjYIZswgJ50i1G6WgeiT1RZK/skzNlcDYeqmVf7471shprlH3vDIy5PQcCCMRG2kJfvE8dTLXnMJy7J4hiCRN0M7Eo9WRnd68lWiI9VHIkJK+MhwhKozzMnuK438+vSkp45DqXuq3luVC8rRd1d/7zuXaT7PE2Lxb6YUUHJ+5zYjJTLFOBoXCZAaSTU2HQ95WaOBPP95ghMpT6veSa+RLVPi1mx6Lsyg7Rm7Hk4+gegCgPYLaHXAboDu5oK9Yriem6qyO1VgPgYw7lShrx9anv1U+Eg4avlQDkGUuPvvUiOfyYYkKam8MH0SVdHYebKhRTMC3KTDnK7fwg4qoUUqOI+EF0EcBMzOEC5lFrFD0FW0Ix82F8mV6il/It/Mt4oNi9UUHKHbbUNjQuwy57pDnme40TbDcxD06RoS6UtrZoiwjedOIqSHPpq26ahYXzTj3YtL8kV/XlOkXIrnKenr2QXGV8vMF+/tjIWz4jhF5et2OlDxGKVm8funC85yIEU2253jTz9/k66imPce+w8NBetnNmowFm1nOxIXjAhEgEVfJp3xCYKH2thKlFtr/mf1Y69AR6S7OhN06d5642ClWo1RgZUEK0ch8WV1MC+kvRiyoZSJdp0JipY6wg=
