language: node_js
sudo: false
node_js:
- '0.12'
script:
- npm test
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
deploy:
  provider: heroku
  api_key:
    secure: UnKGhGb4WCjhDh2wjmV2lO51rvC1UDt0YxKVVxiEFUg9ryfujAZzzPUliOMszw3CrWo1bJBI1U3hsW5QSanwTbvrpIAa/aUS12C4wuuI+/xysPr4ZLu3WL1ND2+JHqt+ZSWC4xbitR7ZBJtXWQMghRf0rLj5NaU8gBSAqbzL/JiIkxYfAEJBIQWdfUTpk63Z8nbmOaQh7vV4kJp9E82KpbGFNn3Dg4VcEBAv+B0JX2VJgG5lOS4s4RpcK1xY+MSgBHAsJ68iwA4m0oL7C+HY5Lm6lexhrUzgmA3pACK/N/8xCDxThTS5TLGEVXORnyq9ySk93x3b3+wBNCPkdrBp6yxT3gQMJs+zZSwhMICa6YqDbmSlqcNSKcPWhMNvL21Lyq4zNSyNdDDFiVjRJkIvhAA+wmcMyW31aQNdqXAbsKIlvj6DuCb7LrfMIPT42YBb0RMGZvjSwcr2gV7KhJuVcPvK97NjR2sWM2Tk4K1YsTHXNglPYLF8VlqV1t8VJkV/0KIIvUF6462VrRcI9XEpB7x+LR0z9Y1Hm/jub0ap4frXw3vGjZ083OtlNqNmw9mMbXaWlI3fo/ckIFl2dbWkqJpG36XwcJRYksW2VsbpEFQiEpalAFQmdZqnOHR2y+pAtNwiU6gPwvk5HleJKKccn2CfAIoeHJVL6FPENLKAVGc=
  app: marvin-h



