language: node_js
sudo: false
node_js:
- '0.10'
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ok7fsUqoBIKJ4s9pgIykQIq6RnlANTF7V0moqRXjxrvUH6B0rv7WVf6d1Ge4vm/I75V2Cl6cM41ud+6RnbPVAqKvTcgdVoLdbRJ47K3FmlUJmDjvchTalujGZo1IXl2iY/E9a4jyozQJx0hATgb7j15ADJmqnCG0V8TR3kGd9TtcI5bn6t2rwH0aHCID5cYr1N7M5N/h3W6OGGABM3j6a3aE9CYZqh9yPaX4aT2UiJCoKCfYr5y5U0P8ljYSJ1c1Vk5RhuqWc1r1Nw24ZnfccXAHjtVUSv4bE0Cr+2XuG7Z+TYUykhJWNKNGrROq+3lZYCfNIjdTfdcxaMWsGo92BATUMzCP+fTNcOTL1pgzar2srobQ13mbJ9GgWWX4nTdn6U/1S2i9argXrVOyvTpftdvfmGQi4Zeko7HoejjE3d8Ncn3Gv2gtHqoZRfG9KdEAPybxyowOCpqOuElw3ONRYIaX9vtrLcyo0tRBMQFmQ13TxUkBSjH5vsaZT41ivY2kBimApfF0FrveVBNPz+JtJbWxI9nndyM5uqgvL6oJBbF9U9IvNsUd1PAYCopqMlmeobt4JEZoYrFMBvJGwUMTa9RC+0ChmARSHMwBKdjgIxP1LfWJmktjIymblncFvedPViT+tqW2BPMFU7oucSlPOzhxDiS7fyrCQCv3ZomhXGc=
