language: node_js
sudo: false
node_js:
- '0.10'
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: cpEwFKstxLBuIt1MXH66b+7wvaue8xyMHBmOfEhmgJP67B/eeMtCSlUi4k0cXyFaeCgGzYTnV6lVo2H+PTutXDrafgyudaZqSzLV2jv3yshVkNZGiFjxzOMFqRZkIQS58LRoWkKH4tUfu9Uat1K35nNrKFS1jSlvOsWd3XJ7a3Tb2WkSlnIUOmOrjIi5vIvQBrSl3uyUTavl7KV5pp4A2eK0mjtxv+zKBgxeVnC68jwPLItjcuiHvEd+xa3CQkqsRf6KI8zlXHDzEzNvsZaSwtbJYmOW57dj81ZCpE3A77OJ/vEBuf8Fx2cfBTx76rahjUDqq5qHCKFOhfkWzIA2cV7dxegMcvkbX9oy51Q7Dx8iFNkjh2DHhncCOokFue4i+tW25ZQS56hkPXkr7eQnOye55NMBkcsacDgfEgS36PtPdl5NWTTV26Q7++RktW/9plUDb9NVoFg72ipYPSiqW6ZWLtN/VwHw8h+cdeWo+L1weI4o4eKIS4HCOLUvp/XVU9WbDGYLszICKGIdjye0zpfoxl7d2M3NKDziTXYgIXTZW3V2aMqp0OTwznnJOZl4ObjyR6YkcQ51CcesTj+nG7styKYNzV79YkjRSI1/uh+OWmwlvk6FuB7GkI4SSfC/hQUfEDL5/xqvAZuNIyoHJr+WJ+q/QqQ+YseJeow052g=
